# Generated by Django 4.2.9 on 2025-07-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='localtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='alert_time',
            field=models.DateTimeField(),
        ),
    ]
